const ActionTypeEnum = {
  NOTE_GET_SUCCESS: "NOTE_GET_SUCCESS",
  NOTE_CREATE_REQUEST: "NOTE_CREATE_REQUEST",
  NOTE_REMOVE_SUCCESS: "NOTE_REMOVE_SUCCESS",
  NOTE_REMOVE_REQUEST: "NOTE_REMOVE_REQUEST",
  NOTE_UPDATE_REQUEST: 'NOTE_UPDATE_REQUEST',
  NOTE_UPDATE_SUCCESS: 'NOTE_UPDATE_SUCCESS'
};

export default ActionTypeEnum;
