const ActionTypeEnum = {
  NOTE_GET_SUCCESS: "NOTE_GET_SUCCESS",
  NOTE_CREATE_REQUEST: "NOTE_CREATE_REQUEST",
  NOTE_REMOVE_SUCCESS: "NOTE_REMOVE_SUCCESS",
  NOTE_REMOVE_REQUEST: "NOTE_REMOVE_REQUEST",
};

export default ActionTypeEnum;
