import type { NextPage } from 'next'
import Head from 'next/head'
import MainPage from '../components/MainPage'
import PracticeTS from '../components/PracticeTS'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Note App By TS-Saga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
      {/* <PracticeTS /> */}
    </div>
  )
}

export default Home
